### ISSUE TITLE
Does not add as a plugin in modern nushell

### ISSUE THREAD

**Issue by ktlknss** [WindSoilder/nu_plugin_formats#1]
Firstly the readme is out of date (it says to use `register nu_plugin_formats` but it should be `plugin add nu_plugin_formats`) but also when I add the plugin it says
```sh
$ plugin add nu_plugin_formats # in .../target/release and .../target/debug
Error: nu::shell::plugin_failed_to_decode

  × Plugin failed to decode: unknown variant `Error`, expected one of
  │ `Hello`, `Option`, `CallResponse`, `EngineCall`, `Data`, `End`,
  │ `Drop`, `Ack`
```

**Comment by WindSoilder** [comment]
Thank you for reporting this!
Yeah nushell have a big upgrade since last year, I will update the code to fit the new version

**Comment by WindSoilder** [comment]
Ok, I think the repo is too outdated, it's good to use [nu_plugin_formats](https://github.com/nushell/nushell/tree/main/crates/nu_plugin_formats) directly.
For this reason, I will archive this repo soon
